public class Main {
    public static void main(String[] args) {

        int a = 39017;
        byte b = 111;
        short c = -18250;
        long d = 21628733648L;
        float e = 2.1e+12f;
        double f = 4e+147;
        System.out.println("Значение переменной a с типом int равно " + a);
        System.out.println("Значение переменной b с типом byte равно " + b);
        System.out.println("Значение переменной c с типом short равно " + c);
        System.out.println("Значение переменной d с типом long равно " + d);
        System.out.println("Значение переменной e с типом float равно " + e);
        System.out.println("Значение переменной f с типом double равно " + f);
        float One = 27.12f;
        long Two = 987678965549L;
        float Three = 2.786f;
        short Four = 569;
        short Five = -159;
        short Six = 27897;
        byte Seven = 67;
        System.out.println(One + " переменная float");
        System.out.println(Two + " переменная long");
        System.out.println(Three + " переменная float");
        System.out.println(Four + " переменная short");
        System.out.println(Five + " переменная short");
        System.out.println(Six + " переменная short");
        System.out.println(Seven + " переменная byte");
        byte LudPav = 23;
        byte AnnSer = 27;
        byte EktAnd = 30;
        int TotalPaper = 480;
        int PaperEveryOne = TotalPaper / (LudPav + AnnSer + EktAnd);
        System.out.println("На каждого ученика рассчитано " + PaperEveryOne + " листов бумаги");
        int Perf2Min = 16;
        int Perf20Min = Perf2Min * 10;
        int Perf24H = Perf2Min / 2 * 60 * 24;
        int Perf3Day = Perf24H * 3;
        int Perf1Mon = Perf24H * 30;
        System.out.println("За 20 минут машина произвела " + Perf20Min + " штук бутылок");
        System.out.println("За 1 сутки машина произвела " + Perf24H + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + Perf3Day + " штук бутылок");
        System.out.println("За 1 месяц машина произвела " + Perf1Mon + " штук бутылок");
        int TotalCans = 120;
        int WhiteCansClass = 2;
        int GrowCansClass = 4;
        int CansOneClass = WhiteCansClass + GrowCansClass;
        int TotalClass = TotalCans / CansOneClass;
        int TotalCansWhite = TotalClass * WhiteCansClass;
        int TotalCansGrow = TotalClass * GrowCansClass;
        System.out.println("В школе, где " + TotalClass + " классов, нужно " + TotalCansWhite + " банок белой красик и " + TotalCansGrow + " банок коричневой краски");
        int Banana = 80;
        int Milk = 105;
        int IceCream = 100;
        int Egg = 70;
        int Breakfast = Banana * 5 + Milk * 2 + IceCream * 2 + Egg * 4;
        float BreakfastKg = Breakfast / 1000f;
        System.out.println("Выход завтрака: " + Breakfast + " грамм");
        System.out.println("Выход завтрака: " + BreakfastKg + " килограмм");
        int TotalWeight = 7;
        float MinWeight = 0.25f;
        float MaxWeight = 0.5f;
        float AvWeight = (MinWeight + MaxWeight) / 2;
        float MinDay = TotalWeight / MaxWeight;
        float MaxDay = TotalWeight / MinWeight;
        float AvDay = TotalWeight / AvWeight;
        System.out.println("Минимум потребуется " + MinDay + " дней");
        System.out.println("Максимум " + MaxDay + " дней");
        System.out.println("При снижении веса в среднем " + AvDay + " дней");
        int Masha = 67760;
        int Denis = 83690;
        int Kris = 76230;
        int MashaYear = Masha * 12;
        int DenisYear = Denis * 12;
        int KrisYear = Kris * 12;
        Masha = Masha + Masha / 10;
        Denis = Denis + Denis / 10;
        Kris = Kris + Kris / 10;
        int MashaNewYear = Masha * 12;
        int DenisNewYear = Denis * 12;
        int KrisNewYear = Kris * 12;
        System.out.println("Маша теперь получает " + Masha + " рублей. Годовой доход вырос на " + (MashaNewYear - MashaYear));
        System.out.println("Денис теперь получает " + Denis + " рублей. Годовой доход вырос на " + (DenisNewYear - DenisYear));
        System.out.println("Кристина теперь получает " + Kris + " рублей. Годовой доход вырос на " + (KrisNewYear - KrisYear));

    }
}