public class Main {
    public static void main(String[] args) {

        int a = 39017;
        byte b = 111;
        short c = -18250;
        long d = 21628733648L;
        float e = 2.1e+12f;
        double f = 4e+147;
        System.out.println("Значение переменной a с типом int равно " + a);
        System.out.println("Значение переменной b с типом byte равно " + b);
        System.out.println("Значение переменной c с типом short равно " + c);
        System.out.println("Значение переменной d с типом long равно " + d);
        System.out.println("Значение переменной e с типом float равно " + e);
        System.out.println("Значение переменной f с типом double равно " + f);
        float oneVariable = 27.12f;
        long twoVariable = 987678965549L;
        float threeVariable = 2.786f;
        short fourVariable = 569;
        short fiveVariable = -159;
        short sixVariable = 27897;
        byte sevenVariable = 67;
        System.out.println(oneVariable + " переменная float");
        System.out.println(twoVariable + " переменная long");
        System.out.println(threeVariable + " переменная float");
        System.out.println(fourVariable + " переменная short");
        System.out.println(fiveVariable + " переменная short");
        System.out.println(sixVariable + " переменная short");
        System.out.println(sevenVariable + " переменная byte");
        byte ludPav = 23;
        byte annSer = 27;
        byte ektAnd = 30;
        int totalPaper = 480;
        int paperEveryOne = totalPaper / (ludPav + annSer + ektAnd);
        System.out.println("На каждого ученика рассчитано " + paperEveryOne + " листов бумаги");
        int perf2Min = 16;
        int perf20Min = perf2Min * 10;
        int perf24H = perf2Min / 2 * 60 * 24;
        int perf3Day = perf24H * 3;
        int perf1Mon = perf24H * 30;
        System.out.println("За 20 минут машина произвела " + perf20Min + " штук бутылок");
        System.out.println("За 1 сутки машина произвела " + perf24H + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + perf3Day + " штук бутылок");
        System.out.println("За 1 месяц машина произвела " + perf1Mon + " штук бутылок");
        int totalCans = 120;
        int whiteCansClass = 2;
        int growCansClass = 4;
        int cansOneClass = whiteCansClass + growCansClass;
        int totalClass = totalCans / cansOneClass;
        int totalCansWhite = totalClass * whiteCansClass;
        int totalCansGrow = totalClass * growCansClass;
        System.out.println("В школе, где " + totalClass + " классов, нужно " + totalCansWhite + " банок белой красик и " + totalCansGrow + " банок коричневой краски");
        int banana = 80;
        int milk = 105;
        int iceCream = 100;
        int egg = 70;
        int breakfast = banana * 5 + milk * 2 + iceCream * 2 + egg * 4;
        float breakfastKg = breakfast / 1000f;
        System.out.println("Выход завтрака: " + breakfast + " грамм");
        System.out.println("Выход завтрака: " + breakfastKg + " килограмм");
        int totalWeight = 7;
        float minWeight = 0.25f;
        float maxWeight = 0.5f;
        float avWeight = (minWeight + maxWeight) / 2;
        float minDay = totalWeight / maxWeight;
        float maxDay = totalWeight / minWeight;
        float avDay = totalWeight / avWeight;
        System.out.println("Минимум потребуется " + minDay + " дней");
        System.out.println("Максимум " + maxDay + " дней");
        System.out.println("При снижении веса в среднем " + avDay + " дней");
        int masha = 67760;
        int denis = 83690;
        int kris = 76230;
        int mashaYear = masha * 12;
        int denisYear = denis * 12;
        int krisYear = kris * 12;
        masha = masha + masha / 10;
        denis = denis + denis / 10;
        kris = kris + kris / 10;
        int mashaNewYear = masha * 12;
        int denisNewYear = denis * 12;
        int krisNewYear = kris * 12;
        System.out.println("Маша теперь получает " + masha + " рублей. Годовой доход вырос на " + (mashaNewYear - mashaYear));
        System.out.println("Денис теперь получает " + denis + " рублей. Годовой доход вырос на " + (denisNewYear - denisYear));
        System.out.println("Кристина теперь получает " + kris + " рублей. Годовой доход вырос на " + (krisNewYear - krisYear));

    }
}